services:
  db:
    image: postgres:15
    container_name: salon_bot-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER:-app_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-change_me}
      POSTGRES_DB: ${DB_NAME:-booking_app}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-app_user} -d ${DB_NAME:-booking_app}"]
      interval: 3s
      timeout: 5s
      retries: 5

  migrations:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy     # ждём, пока БД реально готова
    env_file:
      - .env
    command: >
      sh -c "
      echo 'Applying migrations...';
      alembic upgrade head &&
      echo 'Migrations completed successfully!'
      "

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: salon_bot-bot
    depends_on:
      migrations:
        condition: service_completed_successfully   # ЭТО САМОЕ ВАЖНОЕ!
      db:
        condition: service_healthy
    env_file:
      - .env
    command: python -m bot.app.run_bot
    restart: unless-stopped

volumes:
  pgdata: